In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from pathlib import Path

In [45]:
YEAR = '2023_full'
INPUT = f'03_URMA_FEAT_ENG_PARQ/URMA_FEAT_ENG_PARQ_{YEAR}.parquet'
OUTPUT = f'04_COMB_DATA_PARQ/COMB_DATA_PARQ_{YEAR}.parquet'

In [46]:
## DIRECTORY FOR ADD'L FEATURE FILES
BASE_DIR =Path('05_RAW_FEAT_DATA/')

def read_file(filename):
    loc = BASE_DIR/f"{filename}.csv"
    df = pd.read_csv(loc)
    return df

In [47]:
calendar = read_file('calendar_reference')
calendar

,date,year,month,day_of_year,day_of_week,quarter,holiday,is_holiday
0,2014-01-01,2014,1,1,Wednesday,1,New Year's Day,True
1,2014-01-02,2014,1,2,Thursday,1,NaN,False
2,2014-01-03,2014,1,3,Friday,1,NaN,False
3,2014-01-04,2014,1,4,Saturday,1,NaN,False
4,2014-01-05,2014,1,5,Sunday,1,NaN,False
...,...,...,...,...,...,...,...,...
4013,2024-12-27,2024,12,362,Friday,4,NaN,False
4014,2024-12-28,2024,12,363,Saturday,4,NaN,False
4015,2024-12-29,2024,12,364,Sunday,4,NaN,False
4016,2024-12-30,2024,12,365,Monday,4,NaN,False
4017,2024-12-31,2024,12,366,Tuesday,4,NaN,False

In [48]:
elec_dmd = read_file('county_electricity_demand')
elec_dmd.head()

,timestamp,Alameda,Alpine,Amador,Butte,Calaveras,Colusa,Contra Costa,Del Norte,El Dorado,...,Sonoma,Stanislaus,Sutter,Tehama,Trinity,Tulare,Tuolumne,Ventura,Yolo,Yuba
0,2016-01-01 00:00:00+00:00,1176.275794,0.812014,26.598339,162.300902,32.192157,15.268580,1062.423344,25.020711,133.662747,...,358.862354,359.101087,68.594283,46.700827,9.284875,300.275290,41.835854,576.225204,153.936470,53.236849
1,2016-01-01 01:00:00+00:00,1190.669213,0.752825,26.923826,164.286880,32.586073,15.455413,1075.423577,26.634949,135.222954,...,363.253536,378.357263,69.433766,45.640673,9.688812,314.084688,40.801315,605.631208,155.826528,53.893551
2,2016-01-01 02:00:00+00:00,1316.228479,0.832196,29.763021,181.611371,36.022361,17.085228,1188.829870,28.915939,149.481856,...,401.559593,421.932353,76.755706,50.452193,10.849582,357.686718,45.118873,692.614804,172.260811,59.575321
3,2016-01-01 03:00:00+00:00,1343.177776,0.849217,30.372405,185.329798,36.759906,17.435041,1213.170733,28.863301,152.540569,...,409.781381,425.966728,78.327210,51.483458,10.992830,366.162775,46.042954,709.338094,175.786680,60.793494
4,2016-01-01 04:00:00+00:00,1303.468389,0.824123,29.474484,179.850752,35.673145,16.919596,1177.304840,27.977224,148.032080,...,397.666701,413.986128,76.011590,49.961326,10.710935,357.772093,44.685079,693.737117,170.590371,58.997260

In [49]:
income = read_file('county_income_data')
income

     year  county_fips     county  est_median_income
0    2024         6001    Alameda             128031
1    2024         6003     Alpine              74440
2    2024         6005     Amador              85625
3    2024         6007      Butte              65143
4    2024         6009  Calaveras              79852
..    ...          ...        ...                ...
517  2016         6107     Tulare              45768
518  2016         6109   Tuolumne              50431
519  2016         6111    Ventura              79470
520  2016         6113       Yolo              63645
521  2016         6115       Yuba              46054

[522 rows x 4 columns]

In [50]:
county_pop = read_file('pop_housing_data')
county_pop

,state_county,date_recorded,total_pop,household_pop,group_quarters_pop,total_households,single_detached,single_attached,two_to_four,five_plus,mobile_homes,occupied,vacancy_rate,person_per_household
0,Alameda,2011-01-01,1527169,1485580,41589,583581,310375,44511,65370,155509,7816,546259,0.064,2.72
1,Alameda,2012-01-01,1549193,1507025,42168,585757,311507,44989,65377,156089,7795,549045,0.063,2.74
2,Alameda,2013-01-01,1575139,1531715,43424,589036,312769,45539,65449,157507,7772,554877,0.058,2.76
3,Alameda,2014-01-01,1597747,1552536,45211,592364,314278,46038,65446,158854,7748,558790,0.057,2.78
4,Alameda,2015-01-01,1622205,1575975,46230,595506,315594,46586,65416,160182,7728,562283,0.056,2.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,Yuba,2021-01-01,81973,79888,2085,29748,21316,570,2636,2356,2870,27266,0.083,2.93
856,Yuba,2022-01-01,82281,80213,2068,30214,21764,570,2640,2356,2884,27831,0.079,2.88
857,Yuba,2023-01-01,83080,80994,2086,30893,22387,572,2646,2404,2884,28302,0.084,2.86
858,Yuba,2024-01-01,84667,82638,2029,31502,22823,572,2664,2553,2890,28830,0.085,2.87
859,Yuba,2025-01-01,85023,82951,2072,32026,23319,575,2682,2553,2897,29309,0.085,2.83

In [51]:
county_pop['state_county'].unique().tolist()

['Alameda',
 'Alpine',
 'Amador',
 'Butte',
 'Calaveras',
 'Colusa',
 'Contra Costa',
 'Del Norte',
 'El Dorado',
 'Fresno',
 'Glenn',
 'Humboldt',
 'Imperial',
 'Inyo',
 'Kern',
 'Kings',
 'Lake',
 'Lassen',
 'Los Angeles',
 'Madera',
 'Marin',
 'Mariposa',
 'Mendocino',
 'Merced',
 'Modoc',
 'Mono',
 'Monterey',
 'Napa',
 'Nevada',
 'Orange',
 'Placer',
 'Plumas',
 'Riverside',
 'Sacramento',
 'San Benito',
 'San Bernardino',
 'San Diego',
 'San Francisco',
 'San Joaquin',
 'San Luis Obispo',
 'San Mateo',
 'Santa Barbara',
 'Santa Clara',
 'Santa Cruz',
 'Shasta',
 'Sierra',
 'Siskiyou',
 'Solano',
 'Sonoma',
 'Stanislaus',
 'Sutter',
 'Tehama',
 'Trinity',
 'Tulare',
 'Tuolumne',
 'Ventura',
 'Yolo',
 'Yuba']

In [52]:
import pandas as pd

feat_daily = pd.read_parquet(INPUT)
feat_daily["date"] = pd.to_datetime(feat_daily["date"])
feat_daily["county"] = feat_daily["county"].astype(str).str.strip()


assert feat_daily.duplicated(["date","county"]).sum() == 0

In [53]:
feat_daily[feat_daily['date'] ==f'{YEAR}-01-01'].count()

date                    0
county                  0
spfh_peak_kgkg_pop      0
tavg_k                  0
dpt_afternoon_k_mean    0
dpt_afternoon_k_pop     0
wind_peak_ms_pop        0
cloud_cover_pct_pop     0
hdd65                   0
cdd75                   0
wind_peak_ms_mean       0
wind_low_ms_mean        0
tmax_k_pop              0
hdd65_pop               0
cdd65_pop               0
wind_low_ms_pop         0
dpt_morning_k_pop       0
trange_k                0
tmin_k                  0
dpt_morning_k_mean      0
cloud_cover_pct_mean    0
cdd75_pop               0
cdd65                   0
tmax_k                  0
tmin_k_pop              0
spfh_peak_kgkg_mean     0
dtype: int64

In [54]:
feat_daily.info()

<class 'pandas.DataFrame'>
RangeIndex: 21535 entries, 0 to 21534
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  21535 non-null  datetime64[ns]
 1   county                21535 non-null  str
 2   spfh_peak_kgkg_pop    21535 non-null  float32
 3   tavg_k                21535 non-null  float32
 4   dpt_afternoon_k_mean  21535 non-null  float32
 5   dpt_afternoon_k_pop   21535 non-null  float32
 6   wind_peak_ms_pop      21535 non-null  float32
 7   cloud_cover_pct_pop   21535 non-null  float32
 8   hdd65                 21535 non-null  float32
 9   cdd75                 21535 non-null  float32
 10  wind_peak_ms_mean     21535 non-null  float32
 11  wind_low_ms_mean      21535 non-null  float32
 12  tmax_k_pop            21535 non-null  float32
 13  hdd65_pop             21535 non-null  float32
 14  cdd65_pop             21535 non-null  float32
 15  wind_low_ms_pop       21535 non-null  float32
 16  dpt_morning_k_pop     21535 non-null  float32
 17  trange_k              21535 non-null  float32
 18  tmin_k                21535 non-null  float32
 19  dpt_morning_k_mean    21535 non-null  float32
 20  cloud_cover_pct_mean  21535 non-null  float32
 21  cdd75_pop             21535 non-null  float32
 22  cdd65                 21535 non-null  float32
 23  tmax_k                21535 non-null  float32
 24  tmin_k_pop            21535 non-null  float32
 25  spfh_peak_kgkg_mean   21535 non-null  float32
dtypes: datetime64[ns](1), float32(24), str(1)
memory usage: 2.5 MB

In [55]:
calendar.head()

,date,year,month,day_of_year,day_of_week,quarter,holiday,is_holiday
0,2014-01-01,2014,1,1,Wednesday,1,New Year's Day,True
1,2014-01-02,2014,1,2,Thursday,1,NaN,False
2,2014-01-03,2014,1,3,Friday,1,NaN,False
3,2014-01-04,2014,1,4,Saturday,1,NaN,False
4,2014-01-05,2014,1,5,Sunday,1,NaN,False

In [56]:
calendar['date'] = pd.to_datetime(calendar['date'])

In [57]:
def safe_merge(left, right, on, how="left", name="right"):
    before = len(left)
    out = left.merge(right, on=on, how=how)
    after = len(out)
    if after != before:
        raise ValueError(f"Row count changed after merging {name}: {before} -> {after}. Likely a many-to-many join on {on}.")
    return out

In [58]:
feat_daily_add = safe_merge(feat_daily,calendar,'date')
feat_daily_add.head()

,date,county,spfh_peak_kgkg_pop,tavg_k,dpt_afternoon_k_mean,dpt_afternoon_k_pop,wind_peak_ms_pop,cloud_cover_pct_pop,hdd65,cdd75,...,tmax_k,tmin_k_pop,spfh_peak_kgkg_mean,year,month,day_of_year,day_of_week,quarter,holiday,is_holiday
0,2023-01-01,Alameda,0.005102,282.956177,275.448639,277.235779,3.636453,2.043547,8.527161,0.0,...,286.555695,279.461243,0.004617,2023,1,1,Sunday,1,New Year's Day,True
1,2023-01-01,Alpine,0.003137,270.630432,265.026306,267.415070,3.254657,59.734463,20.852905,0.0,...,274.820526,269.059509,0.002763,2023,1,1,Sunday,1,New Year's Day,True
2,2023-01-01,Amador,0.005615,279.877258,274.835480,277.689148,2.676783,1.475736,11.606079,0.0,...,283.842010,277.880066,0.004880,2023,1,1,Sunday,1,New Year's Day,True
3,2023-01-01,Butte,0.004301,280.964355,272.293304,274.719025,5.551710,3.908601,10.518982,0.0,...,284.241913,279.704041,0.003785,2023,1,1,Sunday,1,New Year's Day,True
4,2023-01-01,Calaveras,0.005407,280.467285,275.696564,277.145264,3.262043,3.960532,11.016052,0.0,...,284.083160,278.285492,0.005098,2023,1,1,Sunday,1,New Year's Day,True

In [59]:
elec_dmd["timestamp"] = pd.to_datetime(elec_dmd["timestamp"], utc=True)
elec_dmd

,timestamp,Alameda,Alpine,Amador,Butte,Calaveras,Colusa,Contra Costa,Del Norte,El Dorado,...,Sonoma,Stanislaus,Sutter,Tehama,Trinity,Tulare,Tuolumne,Ventura,Yolo,Yuba
0,2016-01-01 00:00:00+00:00,1176.275794,0.812014,26.598339,162.300902,32.192157,15.268580,1062.423344,25.020711,133.662747,...,358.862354,359.101087,68.594283,46.700827,9.284875,300.275290,41.835854,576.225204,153.936470,53.236849
1,2016-01-01 01:00:00+00:00,1190.669213,0.752825,26.923826,164.286880,32.586073,15.455413,1075.423577,26.634949,135.222954,...,363.253536,378.357263,69.433766,45.640673,9.688812,314.084688,40.801315,605.631208,155.826528,53.893551
2,2016-01-01 02:00:00+00:00,1316.228479,0.832196,29.763021,181.611371,36.022361,17.085228,1188.829870,28.915939,149.481856,...,401.559593,421.932353,76.755706,50.452193,10.849582,357.686718,45.118873,692.614804,172.260811,59.575321
3,2016-01-01 03:00:00+00:00,1343.177776,0.849217,30.372405,185.329798,36.759906,17.435041,1213.170733,28.863301,152.540569,...,409.781381,425.966728,78.327210,51.483458,10.992830,366.162775,46.042954,709.338094,175.786680,60.793494
4,2016-01-01 04:00:00+00:00,1303.468389,0.824123,29.474484,179.850752,35.673145,16.919596,1177.304840,27.977224,148.032080,...,397.666701,413.986128,76.011590,49.961326,10.710935,357.772093,44.685079,693.737117,170.590371,58.997260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70123,2023-12-31 19:00:00+00:00,1112.255689,1.209585,35.235351,238.237317,32.675302,24.664309,1320.245271,21.463129,215.247218,...,526.023429,354.007688,113.534740,44.192736,10.287190,442.783800,46.012491,580.072486,194.696677,82.758134
70124,2023-12-31 20:00:00+00:00,1055.092955,1.159295,33.771844,194.812998,32.029685,23.079586,1245.316113,20.741699,213.863784,...,487.459845,353.955585,104.881917,43.286213,10.231887,442.903007,42.371315,594.845204,183.808947,77.217619
70125,2023-12-31 21:00:00+00:00,1054.860926,1.240593,32.127470,149.253645,30.280650,21.040979,1074.005315,20.097224,207.564491,...,438.905709,333.236584,93.264717,44.195339,10.024835,409.739936,45.779708,569.597155,178.064486,70.445801
70126,2023-12-31 22:00:00+00:00,1029.774362,1.155394,33.998702,144.210658,29.155542,17.540855,1028.575606,19.301610,187.959091,...,348.560520,328.038264,74.663032,43.622879,10.162397,343.739788,40.471156,594.441439,158.898974,57.419940
70127,2023-12-31 23:00:00+00:00,1032.826742,1.014924,27.108626,132.007771,28.977349,13.919769,975.432191,18.949506,160.993133,...,305.058903,325.598723,61.001041,44.917020,10.040192,308.114920,38.801025,566.508536,139.206057,53.340979

In [60]:
elec_dmd["timestamp"].dtype

datetime64[us, UTC]

In [61]:
# Unpivot the DataFrame using pd.melt()
elec_melt = pd.melt(elec_dmd,
                  id_vars=['timestamp'],
                  var_name='county',
                  value_name='load_mw')

print(elec_melt)

                        timestamp   county      load_mw
0       2016-01-01 00:00:00+00:00  Alameda  1176.275794
1       2016-01-01 01:00:00+00:00  Alameda  1190.669213
2       2016-01-01 02:00:00+00:00  Alameda  1316.228479
3       2016-01-01 03:00:00+00:00  Alameda  1343.177776
4       2016-01-01 04:00:00+00:00  Alameda  1303.468389
...                           ...      ...          ...
4067419 2023-12-31 19:00:00+00:00     Yuba    82.758134
4067420 2023-12-31 20:00:00+00:00     Yuba    77.217619
4067421 2023-12-31 21:00:00+00:00     Yuba    70.445801
4067422 2023-12-31 22:00:00+00:00     Yuba    57.419940
4067423 2023-12-31 23:00:00+00:00     Yuba    53.340979

[4067424 rows x 3 columns]

In [62]:
elec_peak_daily_county = elec_melt.rename(columns={"timestamp": "date"})
elec_peak_daily_county

                             date   county      load_mw
0       2016-01-01 00:00:00+00:00  Alameda  1176.275794
1       2016-01-01 01:00:00+00:00  Alameda  1190.669213
2       2016-01-01 02:00:00+00:00  Alameda  1316.228479
3       2016-01-01 03:00:00+00:00  Alameda  1343.177776
4       2016-01-01 04:00:00+00:00  Alameda  1303.468389
...                           ...      ...          ...
4067419 2023-12-31 19:00:00+00:00     Yuba    82.758134
4067420 2023-12-31 20:00:00+00:00     Yuba    77.217619
4067421 2023-12-31 21:00:00+00:00     Yuba    70.445801
4067422 2023-12-31 22:00:00+00:00     Yuba    57.419940
4067423 2023-12-31 23:00:00+00:00     Yuba    53.340979

[4067424 rows x 3 columns]

In [63]:
# Clean county strings
elec_peak_daily_county["county"] = elec_peak_daily_county["county"].astype(str).str.strip()

# Force date to midnight (drop time)
d = pd.to_datetime(elec_peak_daily_county["date"])
elec_peak_daily_county["date"] = d.dt.floor("D").dt.tz_localize(None)   # sets to midnight

In [64]:
elec_peak_daily_county["date"].dtype

dtype('<M8[us]')

In [65]:
feat_daily_add['date'].dtype

dtype('<M8[ns]')

In [66]:
elec_peak_daily_county = (
    elec_peak_daily_county
    .groupby(["date", "county"], as_index=False, observed=True)["load_mw"]
    .max()
)
elec_peak_daily_county

             date     county      load_mw
0      2016-01-01    Alameda  1343.177776
1      2016-01-01     Alpine     0.958875
2      2016-01-01     Amador    31.425733
3      2016-01-01      Butte   192.146384
4      2016-01-01  Calaveras    39.569402
...           ...        ...          ...
169471 2023-12-31     Tulare   452.289611
169472 2023-12-31   Tuolumne    52.004808
169473 2023-12-31    Ventura   604.920501
169474 2023-12-31       Yolo   194.696677
169475 2023-12-31       Yuba    82.758134

[169476 rows x 3 columns]

In [67]:
feat_daily_add2 = feat_daily_add.merge(
    elec_peak_daily_county,
    on=["date","county"],
    how="left"
)
feat_daily_add2.shape

(21535, 34)

In [68]:
feat_daily_add.shape

(21535, 33)

In [69]:
income.head()

   year  county_fips     county  est_median_income
0  2024         6001    Alameda             128031
1  2024         6003     Alpine              74440
2  2024         6005     Amador              85625
3  2024         6007      Butte              65143
4  2024         6009  Calaveras              79852

In [70]:
feat_daily_add2['year'].dtype

dtype('int64')

In [71]:
feat_daily_add3 = feat_daily_add2.merge(
    income,
    on=["year","county"],
    how="left"
)
feat_daily_add3.columns.to_list()

['date',
 'county',
 'spfh_peak_kgkg_pop',
 'tavg_k',
 'dpt_afternoon_k_mean',
 'dpt_afternoon_k_pop',
 'wind_peak_ms_pop',
 'cloud_cover_pct_pop',
 'hdd65',
 'cdd75',
 'wind_peak_ms_mean',
 'wind_low_ms_mean',
 'tmax_k_pop',
 'hdd65_pop',
 'cdd65_pop',
 'wind_low_ms_pop',
 'dpt_morning_k_pop',
 'trange_k',
 'tmin_k',
 'dpt_morning_k_mean',
 'cloud_cover_pct_mean',
 'cdd75_pop',
 'cdd65',
 'tmax_k',
 'tmin_k_pop',
 'spfh_peak_kgkg_mean',
 'year',
 'month',
 'day_of_year',
 'day_of_week',
 'quarter',
 'holiday',
 'is_holiday',
 'load_mw',
 'county_fips',
 'est_median_income']

In [72]:
feat_daily_add3.shape

(21535, 36)

In [73]:
feat_daily_add2.shape

(21535, 34)

In [74]:
county_pop.head()

,state_county,date_recorded,total_pop,household_pop,group_quarters_pop,total_households,single_detached,single_attached,two_to_four,five_plus,mobile_homes,occupied,vacancy_rate,person_per_household
0,Alameda,2011-01-01,1527169,1485580,41589,583581,310375,44511,65370,155509,7816,546259,0.064,2.72
1,Alameda,2012-01-01,1549193,1507025,42168,585757,311507,44989,65377,156089,7795,549045,0.063,2.74
2,Alameda,2013-01-01,1575139,1531715,43424,589036,312769,45539,65449,157507,7772,554877,0.058,2.76
3,Alameda,2014-01-01,1597747,1552536,45211,592364,314278,46038,65446,158854,7748,558790,0.057,2.78
4,Alameda,2015-01-01,1622205,1575975,46230,595506,315594,46586,65416,160182,7728,562283,0.056,2.80

In [75]:
county_pop['date_recorded']=pd.to_datetime(county_pop['date_recorded'])
county_pop['date_recorded'].dtype

dtype('<M8[us]')

In [76]:
county_pop['year']=county_pop['date_recorded'].dt.year
county_pop.head()

,state_county,date_recorded,total_pop,household_pop,group_quarters_pop,total_households,single_detached,single_attached,two_to_four,five_plus,mobile_homes,occupied,vacancy_rate,person_per_household,year
0,Alameda,2011-01-01,1527169,1485580,41589,583581,310375,44511,65370,155509,7816,546259,0.064,2.72,2011
1,Alameda,2012-01-01,1549193,1507025,42168,585757,311507,44989,65377,156089,7795,549045,0.063,2.74,2012
2,Alameda,2013-01-01,1575139,1531715,43424,589036,312769,45539,65449,157507,7772,554877,0.058,2.76,2013
3,Alameda,2014-01-01,1597747,1552536,45211,592364,314278,46038,65446,158854,7748,558790,0.057,2.78,2014
4,Alameda,2015-01-01,1622205,1575975,46230,595506,315594,46586,65416,160182,7728,562283,0.056,2.80,2015

In [77]:
county_pop=county_pop.rename(columns={"state_county": "county"})

In [78]:
feat_daily_add4 = feat_daily_add3.merge(
    county_pop,
    on=["year","county"],
    how="left"
)
feat_daily_add4.columns.to_list()

['date',
 'county',
 'spfh_peak_kgkg_pop',
 'tavg_k',
 'dpt_afternoon_k_mean',
 'dpt_afternoon_k_pop',
 'wind_peak_ms_pop',
 'cloud_cover_pct_pop',
 'hdd65',
 'cdd75',
 'wind_peak_ms_mean',
 'wind_low_ms_mean',
 'tmax_k_pop',
 'hdd65_pop',
 'cdd65_pop',
 'wind_low_ms_pop',
 'dpt_morning_k_pop',
 'trange_k',
 'tmin_k',
 'dpt_morning_k_mean',
 'cloud_cover_pct_mean',
 'cdd75_pop',
 'cdd65',
 'tmax_k',
 'tmin_k_pop',
 'spfh_peak_kgkg_mean',
 'year',
 'month',
 'day_of_year',
 'day_of_week',
 'quarter',
 'holiday',
 'is_holiday',
 'load_mw',
 'county_fips',
 'est_median_income',
 'date_recorded',
 'total_pop',
 'household_pop',
 'group_quarters_pop',
 'total_households',
 'single_detached',
 'single_attached',
 'two_to_four',
 'five_plus',
 'mobile_homes',
 'occupied',
 'vacancy_rate',
 'person_per_household']

In [79]:
y=feat_daily_add4.shape
print(f'y should be 49 {y}')

y should be 49 (21535, 49)

In [80]:
feat_daily_add4

,date,county,spfh_peak_kgkg_pop,tavg_k,dpt_afternoon_k_mean,dpt_afternoon_k_pop,wind_peak_ms_pop,cloud_cover_pct_pop,hdd65,cdd75,...,group_quarters_pop,total_households,single_detached,single_attached,two_to_four,five_plus,mobile_homes,occupied,vacancy_rate,person_per_household
0,2023-01-01,Alameda,0.005102,282.956177,275.448639,277.235779,3.636453,2.043547,8.527161,0.0,...,50817.0,641809.0,326691.0,51679.0,67035.0,188793.0,7611.0,610393.0,0.049,2.63
1,2023-01-01,Alpine,0.003137,270.630432,265.026306,267.415070,3.254657,59.734463,20.852905,0.0,...,52.0,1550.0,928.0,17.0,38.0,543.0,24.0,527.0,0.660,2.15
2,2023-01-01,Amador,0.005615,279.877258,274.835480,277.689148,2.676783,1.475736,11.606079,0.0,...,4119.0,19070.0,15735.0,602.0,605.0,729.0,1399.0,15915.0,0.165,2.25
3,2023-01-01,Butte,0.004301,280.964355,272.293304,274.719025,5.551710,3.908601,10.518982,0.0,...,5187.0,93243.0,57312.0,3055.0,8972.0,12890.0,11014.0,86124.0,0.076,2.34
4,2023-01-01,Calaveras,0.005407,280.467285,275.696564,277.145264,3.262043,3.960532,11.016052,0.0,...,424.0,27741.0,24208.0,368.0,639.0,378.0,2148.0,18974.0,0.316,2.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21530,2023-12-31,Tulare,0.007219,276.224884,274.121674,282.319580,0.922640,54.731625,15.258453,0.0,...,5680.0,154698.0,118040.0,4105.0,12381.0,10072.0,10100.0,145837.0,0.057,3.23
21531,2023-12-31,Tuolumne,0.005925,274.417877,272.588379,278.279938,0.762568,72.855652,17.065460,0.0,...,3471.0,31589.0,25272.0,316.0,1217.0,1437.0,3347.0,22829.0,0.277,2.24
21532,2023-12-31,Ventura,0.007929,282.145996,280.591095,283.636383,3.109751,80.507843,9.337341,0.0,...,12502.0,296892.0,187968.0,33413.0,16086.0,48546.0,10879.0,283040.0,0.047,2.89
21533,2023-12-31,Yolo,0.007730,285.025818,283.129700,283.528473,1.293290,79.913612,6.457520,0.0,...,15608.0,83172.0,49687.0,5116.0,6571.0,18233.0,3565.0,79458.0,0.045,2.59
21534,2023-12-31,Yuba,0.007424,282.866455,281.610016,282.841461,1.396902,76.767937,8.616882,0.0,...,2086.0,30893.0,22387.0,572.0,2646.0,2404.0,2884.0,28302.0,0.084,2.86

In [81]:
feat_daily_add4.to_parquet(
    "feat_final.parquet",
    index=False,
    compression="snappy"
)

In [82]:
feat_daily_add4.isna().sum()

date                        0
county                      0
spfh_peak_kgkg_pop          0
tavg_k                      0
dpt_afternoon_k_mean        0
dpt_afternoon_k_pop         0
wind_peak_ms_pop            0
cloud_cover_pct_pop         0
hdd65                       0
cdd75                       0
wind_peak_ms_mean           0
wind_low_ms_mean            0
tmax_k_pop                  0
hdd65_pop                   0
cdd65_pop                   0
wind_low_ms_pop             0
dpt_morning_k_pop           0
trange_k                    0
tmin_k                      0
dpt_morning_k_mean          0
cloud_cover_pct_mean        0
cdd75_pop                   0
cdd65                       0
tmax_k                      0
tmin_k_pop                  0
spfh_peak_kgkg_mean         0
year                        0
month                       0
day_of_year                 0
day_of_week                 0
quarter                     0
holiday                 20768
is_holiday                  0
load_mw                   365
county_fips               365
est_median_income         365
date_recorded             365
total_pop                 365
household_pop             365
group_quarters_pop        365
total_households          365
single_detached           365
single_attached           365
two_to_four               365
five_plus                 365
mobile_homes              365
occupied                  365
vacancy_rate              365
person_per_household      365
dtype: int64

In [83]:
feat_daily_add4['load_mw']

0        1370.278078
1           1.405864
2          31.516979
3         204.906458
4          44.271901
            ...
21530     452.289611
21531      52.004808
21532     604.920501
21533     194.696677
21534      82.758134
Name: load_mw, Length: 21535, dtype: float64

In [84]:
CSV_OUT = f"06_CSV/{YEAR}_comb.csv"

feat_daily_add4.to_csv(CSV_OUT, index=False)

print("Wrote:", CSV_OUT)

Wrote: 06_CSV/2023_full_comb.csv